import Head from 'next/head'

export default function Home() {
  return (
    <div className='main-bg'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* HEADER */}
      <header>
        <nav>

        </nav>
      </header>

      {/* MAIN */}
      <main></main>

      {/* FOOTER */}
      <footer></footer>
      
    </div>
  )
}
