import Head from 'next/head'
import Header from '../components/Header'

export default function Home() {
  return (
    <div className='main-bg'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* HEADER */}
      <Header />
      

      {/* MAIN */}
      <main></main>

      {/* FOOTER */}
      <footer></footer>
      
    </div>
  )
}
